# Check correct user - 201, {body}
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Name",
  "lastName": "Surname",
  "email": "testmail5@mail.com",
  "passwordHash": "qwerty",
  "gender": "male",
  "birthday": "10-10-1990"
}

# Check uncorrect user (ununique email) - 500 Server Error
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Name",
  "lastName": "Surname",
  "email": "testmail1@mail.com",
  "passwordHash": "qwerty",
  "gender": "male",
  "birthday": "10-10-1990"
}